/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedItemsSlugRouteImport } from './routes/_authenticated/items.$slug'
import { Route as AuthenticatedDispatchSlugRouteImport } from './routes/_authenticated/dispatch.$slug'
import { Route as AuthenticatedCategorySlugRouteImport } from './routes/_authenticated/category.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsSlugRoute = AuthenticatedItemsSlugRouteImport.update({
  id: '/items/$slug',
  path: '/items/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatchSlugRoute =
  AuthenticatedDispatchSlugRouteImport.update({
    id: '/dispatch/$slug',
    path: '/dispatch/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategorySlugRoute =
  AuthenticatedCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/dispatch/$slug': typeof AuthenticatedDispatchSlugRoute
  '/items/$slug': typeof AuthenticatedItemsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/dispatch/$slug': typeof AuthenticatedDispatchSlugRoute
  '/items/$slug': typeof AuthenticatedItemsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/category/$slug': typeof AuthenticatedCategorySlugRoute
  '/_authenticated/dispatch/$slug': typeof AuthenticatedDispatchSlugRoute
  '/_authenticated/items/$slug': typeof AuthenticatedItemsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/approvals'
    | '/dashboard'
    | '/category/$slug'
    | '/dispatch/$slug'
    | '/items/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approvals'
    | '/dashboard'
    | '/category/$slug'
    | '/dispatch/$slug'
    | '/items/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/approvals'
    | '/_authenticated/dashboard'
    | '/_authenticated/category/$slug'
    | '/_authenticated/dispatch/$slug'
    | '/_authenticated/items/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$slug': {
      id: '/_authenticated/items/$slug'
      path: '/items/$slug'
      fullPath: '/items/$slug'
      preLoaderRoute: typeof AuthenticatedItemsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dispatch/$slug': {
      id: '/_authenticated/dispatch/$slug'
      path: '/dispatch/$slug'
      fullPath: '/dispatch/$slug'
      preLoaderRoute: typeof AuthenticatedDispatchSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category/$slug': {
      id: '/_authenticated/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AuthenticatedCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCategorySlugRoute: typeof AuthenticatedCategorySlugRoute
  AuthenticatedDispatchSlugRoute: typeof AuthenticatedDispatchSlugRoute
  AuthenticatedItemsSlugRoute: typeof AuthenticatedItemsSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCategorySlugRoute: AuthenticatedCategorySlugRoute,
  AuthenticatedDispatchSlugRoute: AuthenticatedDispatchSlugRoute,
  AuthenticatedItemsSlugRoute: AuthenticatedItemsSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
